### PR TITLE
travis-ci support added

### PR DESCRIPTION
**Pull request by olegabr**
the official memcached docker image travis config was used as a base

### CODE REVIEW

**Comment by thresheek** [comment]
Why is that needed?

**Comment by olegabr** [comment]
These tests include some security checks. It is useful to be sure that the docker image you are using is not vulnerable for some common attacks. Thank you.

**Comment by alessfg** [comment]
Integrating support for travis-ci also allows creating an automated suite of tests to verify/ensure that all updates to Dockerfile produce fully functional Docker images.

**Comment by thresheek** [comment]
Closing this one since I don't feel like using Travis will improve things for this repo.

**Pull request closed without merging**
