### PR TITLE
Keep repo key registered in alpine, and simplify Dockerfiles

### PR DESCRIPTION
**Pull request by orgads**
### Proposed changes

Simplify package installation in non-slim variants.

This can also be used in user images to install packages directly.

### Checklist

Before creating a PR, run through this checklist and mark each as complete:
- [X] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/docker-nginx/blob/master/CONTRIBUTING.md) document
- [X] I have run `./update.sh` and ensured all entrypoint/Dockerfile template changes have been applied to the relevant image entrypoint scripts & Dockerfiles
- [X] If applicable, I have added tests that prove my fix is effective or that my feature works
- [X] If applicable, I have checked that any relevant tests pass after adding my changes
- [X] I have updated any relevant documentation

### CODE REVIEW

**Comment by thresheek** [comment]
Hi @orgads !

We did that because we explicitely did not want the image to have the repository configured - as adding more packages with the repos configured might upgrade the packages to something newer than specified initially.  This is also consistent with what we have for Debian-based images.

**Comment by orgads** [comment]
I see. I now changed it to just keep the key registered, but not register the repo. I see this is also done in debian. What do you say?

**Comment by orgads** [comment]
And simplified debian perl and otel to use the existing key too.

**Comment by orgads** [comment]
@thresheek I think the build fails because it tries to build all alpine in parallel, so the non-slim variants use the existing image as base, and this change introduces a dependency between slim and non-slim variants.

**Pull request merged**
