### PR TITLE
Bump 1.11.3

### PR DESCRIPTION
**Pull request by mattrobenolt**
✨

### CODE REVIEW

**Comment by styfle** [comment]
Looking forward to this. I noticed that `1.11.2` doesn't have a tag so hopefully there will be one for `1.11.3`.

https://hub.docker.com/r/library/nginx/tags/

**Comment by florianreinhart** [comment]
Also waiting for this. Would it be possible to get docker-nginx updates faster whenever a new nginx version is released?

**Comment by samkelleher** [comment]
Alpine 3.4 is queued with this release also (3.3 has a DNS resolution issue that makes it incompatible with the latest docker version). Running NGINX on Alpine is the only way to get HTTP/2 to work on Docker, hence the urgency.

**Comment by samkelleher** [comment]
Bump @thresheek - is there a barrier to release. New NGINX and Alpine versions pending.

**Comment by Sepstein** [comment]
Looking forward to this. Any update?

**Comment by thresheek** [comment]
Fixed by https://github.com/nginxinc/docker-nginx/commit/1f7e3c6473c2c6211c305d85cdfcfd733fe1b348

**Comment by samkelleher** [comment]
Awesome welcome back @thresheek! So glad to see this merged in! 🎉

**Comment by styfle** [comment]
Welcome back @thresheek! Will there be a `1.11.3-alpine` variant?

**Comment by mattrobenolt** [comment]
Yes, as soon as this gets pushed: https://github.com/docker-library/official-images/pull/2084

**Pull request closed without merging**
