### PR TITLE
Replace envsubst with Perl script

### PR DESCRIPTION
**Pull request by LeviPesin**
Replace envsubst usage with a Perl script based on https://unix.stackexchange.com/a/294836 to remove the need of installing `gettext` and using `envsubst`.

Would be great if somebody knowing Perl check the script (I don't know Perl very well)...

### CODE REVIEW

**Comment by thresheek** [comment]
Alpine images don't ship perl so this won't be usable there.

**Comment by LeviPesin** [comment]
I think they do? Docs of Alpine Linux state that Perl is there and [Perl works in its online implementation](https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192).

**Comment by thresheek** [comment]
You can try it yourself: `docker run nginx:alpine perl`

**Comment by LeviPesin** [comment]
Closing, then...

**Pull request closed without merging**
