### PR TITLE
Allow specifying different version of Nginx when building modules

### PR DESCRIPTION
**Pull request by rptmat57**

### CODE REVIEW

**Comment by thresheek** [comment]
Hi @rptmat57

Thanks for the contribution - looks good!

Can you please get rid of a merge commit?

**Comment by rptmat57** [comment]
Alright it should be good now

**Comment by thresheek** [comment]
See https://github.com/nginxinc/docker-nginx/pull/815 for some changes in the variable name to redefine the image. Or specifically https://github.com/nginxinc/docker-nginx/commit/22e65b3df3acef8ba2bb517191f2e495782dbbeb

**Comment by rptmat57** [comment]
Thanks for fixing that, sorry for introducing the bug!

**Pull request merged**
