### PR TITLE
bump nginx alpine base image to 3.14

### PR DESCRIPTION
**Pull request by meldafrawi**
Ref: https://github.com/nginxinc/docker-nginx/issues/551

bump alpine to v3.14

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@gmail.com>
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

### CODE REVIEW

**Comment by thresheek** [comment]
There is no nginx 1.20.2.

**Comment by meldafrawi** [comment]
I've updated the PR, and remove nginx version update

**Comment by thresheek** [comment]
I'll merge this PR when new nginx releases are out (1.20.2, 1.21.1).

**Comment by meldafrawi** [comment]
Thanks @thresheek, I've updated the versions again to reflect the new nginx releases (1.20.2, 1.21.1).

**Comment by thresheek** [comment]
Thanks, but I did it differently.

**Pull request closed without merging**
