### PR TITLE
Upgrade to Debian Buster

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by thresheek** [comment]
Thanks.  Why the apt-transport-https change?

**Comment by tianon** [comment]
https://packages.debian.org/buster/apt-transport-https :tada: :balloon: :cake: 

> This is a dummy transitional package - https support has been moved into the apt package in 1.5. It can be safely removed.

**Comment by thresheek** [comment]
Oh, nice. Thanks @tianon!

**Comment by thresheek** [comment]
Merged in 7956a3fed9b57f4796881c99ec23c03c05945d43 - thank you!

We plan to have 1.17.2 around the 23 July, so buster-based tags will be available shortly after that release date.

**Comment by J0WI** [comment]
What about the stable branch?

**Comment by thresheek** [comment]
No plans for a stable release yet.

**Pull request closed without merging**
