### PR TITLE
Use all cores when compiling

### PR DESCRIPTION
**Pull request by mattrobenolt**
:rocket:

### CODE REVIEW

**Comment by thresheek** [comment]
Sorry, I don't think this is a good idea.  While it does speed up things, nginx compilation time is not long anyway.

Also, to be a good citizen on auto-builders / docker official images builders, I would rather not abuse them this way.  I've also checked a couple of other projects that have official images and are built, they don't use parallel jobs.

**Comment by mattrobenolt** [comment]
For reference from the official library: https://github.com/docker-library/memcached/blob/master/alpine/Dockerfile#L25

:)

**Comment by mattrobenolt** [comment]
And python: https://github.com/docker-library/python/blob/master/3.5/alpine/Dockerfile#L44 probably others if I dug through them all.

**Comment by thresheek** [comment]
Heh, interesting.  I've checked haproxy and couchdb and they both do not have it set.  I'll check with the library folk.

**Comment by mattrobenolt** [comment]
Paging @tianon !

**Comment by tianon** [comment]
We do use `-j$(nproc)`/`-j$(getconf _NPROCESSORS_ONLN)` pretty commonly; anywhere we don't within "docker-library" repos is likely just a case of it compiling so fast that `-j` doesn't make much difference anyhow (`haproxy` and `redis` come to mind).

**Comment by luxas** [comment]
Any chance this could be merged?

**Comment by thresheek** [comment]
Fixed by https://github.com/nginxinc/docker-nginx/commit/e117bd83e9befe5582bc1da8f72248398fffa16c

Thanks!

**Pull request closed without merging**
