### PR TITLE
Extract only envsubst out of gettext

### PR DESCRIPTION
**Pull request by mattrobenolt**
This results in a reduction of ~5.5MB from the image.

```
Before: 59688904 bytes
After:  54104509 bytes
```

### CODE REVIEW

**Comment by thresheek** [comment]
Thank you!

I've pushed the patch manually.

**Comment by md5** [comment]
This seems like it could be problematic if someone needs to have the rest of `gettext` in a derived image. I wonder if it would be possible to split `envsubst` into a separate package in Alpine itself.

**Comment by md5** [comment]
I also wonder how much of the size savings are actually coming from deleting the Nginx source and adding `--no-cache` to the runDeps installation.

**Comment by thresheek** [comment]
Well this is a bit out of scope for the current image; would alpine package manager overwrite the provided /bin/envsubst if gettext is installed by someone using FROM with this image?

**Comment by thresheek** [comment]
nginx source was deleted in the prior versions as well, so it wont make a difference.  the diff is kinda confusing thou.

**Comment by md5** [comment]
I believe the -f flag would be needed, which would only be discoverable
through reading the Dockerfile and seeing that the package is only
partially installed or through trial and error.

**Comment by md5** [comment]
@clandmeter What do you think of breaking out `envsubst` into a `getttext-envsubst` package? I see that there are already a number of subpackages of `gettext`, including `gettext-asprintf`.

**Comment by md5** [comment]
@thresheek I see what you mean about `/usr/src/nginx-$NGINX_VERSION` in the diff. I got confused reading it on my phone.

**Comment by mattrobenolt** [comment]
> What do you think of breaking out envsubst into a getttext-envsubst package?

Also, I'd be open to just moving `envsubst` into say, `/usr/local/bin` instead of putting it back into `/usr/bin`, that we re-installing `gettext` won't have to overwrite anything.

Is that a fair compromise?

**Pull request closed without merging**
