### PR TITLE
Bump to 1.8.0 (stable)

### PR DESCRIPTION
**Pull request by ffung**

### CODE REVIEW

**Comment by thresheek** [comment]
I will bump to 1.9.0 (mainline) when it's out.

**Comment by ffung** [comment]
ok, you don't want to publish a stable version in the hub?

btw there was also a fix in this PR for suppressing the TERM warnings during build

**Comment by thresheek** [comment]
Yes, the idea is to use mainline here, see https://github.com/nginxinc/docker-nginx/issues/3.

as for TERM I don't really want to introduce another layer for a cosmetic change.

**Comment by ffung** [comment]
ok fair enough ;-)

**Pull request closed without merging**
