### PR TITLE
Move CONFIG/GPG_KEYS out of image ENV vars

### PR DESCRIPTION
**Pull request by mattrobenolt**
There's no reason for these to exist as environment variables, and
CONFIG is pretty clunky and useless outside of build time.

I'd argue that if someone wanted to be able to inspect this information,
it could be retrieved from `nginx -V`.

Another point is that these don't exist for the `debian:jessie` based
images either.

### CODE REVIEW

**Comment by thresheek** [comment]
Thank you!

I've pushed the patch manually.

**Comment by cameronmalek** [comment]
Why was `NGINX_VERSION` excluded from this? I can't think of a good reason.

**Comment by mattrobenolt** [comment]
It's much more common practice to leave the software version in environment variables. I don't know the reasoning tbh, but it's exhibited in every official image, so I choose to follow convention.

**Comment by cameronmalek** [comment]
Okay, thanks.

**Pull request closed without merging**
