### PR TITLE
Update to Alpine 3.9

### LINKED ISSUE #159: Docker Hub's vulnerability checker is out of control - all Nginx images are 🚨
I feel that reporting about each separate false positive is crazy. Is there a way to clean it up efficiently?

### PR DESCRIPTION
**Pull request by J0WI**
Fixes #159, #190 and #305

### CODE REVIEW

**Comment by ntimo** [comment]
Any news when this will get merged? :)

**Comment by lubo** [comment]
@thresheek Stop teasing us :smile:

**Comment by thresheek** [comment]
Merged in https://github.com/nginxinc/docker-nginx/commit/2364fdc54af554d28ef95b7be381677d10987986, thanks.

**Comment by Knight1** [comment]
How long does it take till the new images are available on Docker Hub?

**Comment by thresheek** [comment]
It should be live once https://github.com/docker-library/official-images/pull/5377 is merged.

**Pull request closed without merging**
