### PR TITLE
Update mainline to Alpine 3.16

### PR DESCRIPTION
**Pull request by jnoordsij**
Alpine 3.16 was [released](https://alpinelinux.org/posts/Alpine-3.16.0-released.html) yesterday. This PR updates the `mainline` image to use the latest Alpine version.

### CODE REVIEW

**Comment by thresheek** [comment]
Thanks, I'll apply this when I'll build new nginx packages for Alpine 3.16 - currently the builds will fail because there are none.

**Comment by thresheek** [comment]
Done for `stable` images.  When there will be a new release for the `mainline` branch, I'll update it as well.

**Comment by jnoordsij** [comment]
> Done for `stable` images. When there will be a new release for the `mainline` branch, I'll update it as well.

Thanks! Just rebased this for easier merging.

**Review by JAORMX — APPROVED** [review]

**Comment by rmkanda** [comment]
@jnoordsij  Can you merge the changes?

**Comment by jnoordsij** [comment]
> @jnoordsij Can you please merge the changes?

Merge has to be done by a maintainer. See the comments from @thresheek above: this will be merged when the new `mainline` version (1.23) is released.

**Comment by thresheek** [comment]
Which is, if all goes well, will be done tomorrow or on Wednesday :-)

**Pull request merged**
