### PR TITLE
Add OCI labels

### PR DESCRIPTION
**Pull request by lucacome**
Adds labels according to the spec https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

### CODE REVIEW

**Comment by thresheek** [comment]
Hello @lucacome !

Given the fact that we also mirror those containers to other registries, e.g. AWS ECR Public, how should we deal with org.opencontainers.image.base.name?

**Comment by lucacome** [comment]
@thresheek the base images are always coming from docker.io right?

**Comment by thresheek** [comment]
debian:slim and alpine are indeed coming from docker.io, correct.

**Comment by tianon** [comment]
Related: https://github.com/docker-library/official-images/issues/3540, https://github.com/docker-library/official-images/issues/12580 :eyes:

**Comment by tianon** [comment]
Yeah, I personally avoid `LABEL` entirely, but if you do want to use them, they should be compliant to the recommendations for annotations in the OCI's image-spec.

**Pull request closed without merging**
