### PR TITLE
Update nginx to 1.19.4

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jhoelzl** [comment]
Why it is not merged?

**Comment by thresheek** [comment]
Thank you @J0WI for your contribution.  I've been indeed lagging on updating to 1.19.4 here since I'm figuring out a way to provide third-party modules on top of this image.  Also, this PR is not buildable since there was a subtle change in njs package versioning on Debian.  I'll fix that in a subsequent commit.

@jhoelzl we had a nationwide holiday yesterday - sorry for failing your expectations!

**Comment by MindFireGPSDevEleSearch** [comment]
docker plugin install sirlatrom/docker-secretprovider-plugin-vault:dependabot-docker-golang-1-20-4-alpine

**Review by MindFireGPSDevEleSearch — CHANGES_REQUESTED** [review]
.

**Comment by MindFireGPSDevEleSearch** [comment]
> 

9998b924763f4b218659c9b0de35961b317f14c9

**Comment by MindFireGPSDevEleSearch** [comment]
aebdace36df83690ca283405efd283bc750ff41e

**Comment by MindFireGPSDevEleSearch** [comment]
docker plugin install sirlatrom/docker-secretprovider-plugin-vault:dependabot-docker-golang-1-20-5-alpine

**Pull request merged**
