### PR TITLE
Fix typo in 10-listen-on-ipv6-by-default.sh

### PR DESCRIPTION
**Pull request by gurdiga**
Just that. 🤷🏻‍♂️

### CODE REVIEW

**Comment by thresheek** [comment]
I'm not a native english speaker, but to me that's not a typo.  Can anyone weigh in?

**Comment by tianon** [comment]
I think the existing text in the repo was intended to be possessive (ie, should be `package's version`).

Either `packaged` or `package's` seems correct to me 😅

**Comment by adampweb** [comment]
@thresheek That's a typo, because "package" mean "pack" in plurar, "packaged" in turn synonymous with "packed", in singular write 

I'm not a native english speaker too.

**Comment by thresheek** [comment]
Fixed in https://github.com/nginxinc/docker-nginx/commit/a4208f853fa3fcb73a146a268fb2d5f0eee7733b, thank your for the contribution!

**Pull request closed without merging**
